### ISSUE TITLE
API pública

### ISSUE THREAD

**Issue by magnobiet** [magnobiet/states-cities-brazil#2]
- Heroku?
- Getup?
- WeDeploy?
- Firebase?
- ...

**Comment by lubien** [comment]
Eu acho que uma solução vantajosa é você desenvolver um serviço de crawler open source.

* Resolve #1 
* Facilmente hospedável no Heroku por você para quando alguem precisar
* Fácil de ser hospedado localmente caso alguém necessite de uma demanda maior do que o seu serviço do Heroku pode aguentar num Dyno free.
 
Esse é o modelo usado em https://github.com/Rob--W/cors-anywhere/

**Comment by magnobiet** [comment]
Obrigado pela contribuição @lubien.

A ideia é bem essa, fazer algo bem genérico a partir do _crawler_  do IBGE.

Nas próximas semana irei começar a trabalhar um pouco mais nisso, mas contribuições são muito bem vindas.

**Comment by lubien** [comment]
Perfeito
